version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    # Load environment variables from the .env file at the project root
    env_file:
      - .env
    # For live reloading during development (remove or comment out for production if not needed)
    volumes:
      - ./app:/app/app        # Mount your app code for live reloading
      - ./requirements.txt:/app/requirements.txt # Ensure requirements are available for reload
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  # --- REMOVED THE 'redis' SERVICE BLOCK ENTIRELY ---